### PR TITLE
Fix exception when type has an indexed property

### PR DESCRIPTION
**Pull request by ruler501**
Added code to ignore indexed properties and a test to show why this was needed.

### CODE REVIEW

**Comment by ruler501** [comment]
The build failure looks to be a problem with travis. It's failing to install packages

**Comment by thedmi** [comment]
I think generally ignoring the indexed properties is semantically wrong. We should try to treat indexed properties as a dictionary and compare it the same way as a "normal" dictionary property. If the indexed property should still be ignored in some cases, the `[MemberwiseEqualityIgnore]` attribute can be used as usual.

**Comment by zgabi** [comment]
But you cannot get the valid index parameters, so the only way is to ignore them by default.

And maybe you can add a new attrribute, like:
`[MemberwiseEqualityIndexParameters(nameof(Keys))]`, where you can specify the property name which retuns the valid parametrs for the index (`Keys`).

Multiple index parameters are more compilated, in this case the Keys property can return tuples for example.

**Comment by thedmi** [comment]
I've extracted the relevant commit of @ruler501 into a separate PR, see #17 . This PR contains other, unrelated changes, so I'll close this.

**Pull request closed without merging**
