### PR TITLE
Enable building for .Net Framework

### PR DESCRIPTION
**Pull request by ruler501**
Widen support by supporting both .Net Core and .Net Framework

### CODE REVIEW

**Comment by ruler501** [comment]
I don't know enough about Travis-CI .Net support to get it to have 4.6.2 but building on my local machine seems to work

**Comment by zgabi** [comment]
Equ currently targets netstandard 1.5, which is supported by .NET fw 4.6.1. It makes no sense to add another .NET fw target if it is greater or equal to 4.6.1.  Am I wrong?

**Comment by ruler501** [comment]
It does technically support it already, but that requires installing the entirety of the .Net Core SDK which can be a strong deterrent to using it.

**Comment by thedmi** [comment]
@ruler501 I agree with @zgabi . With more and more open source libraries moving to .NET Standard, most .NET Framework projects will eventually reference the .NET Standard libraries (note that this is NOT the .NET Core SDK).

**Pull request closed without merging**
